# permissions for end users to view sampleapiapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sampleapiapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sample-api-operator
    app.kubernetes.io/part-of: sample-api-operator
    app.kubernetes.io/managed-by: kustomize
  name: sampleapiapp-viewer-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - sampleapiapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.example.com
  resources:
  - sampleapiapps/status
  verbs:
  - get
